apiVersion: batch.company.org/v1
kind: PubSubListener
health:
  healthProbeBindAddress: :8081
metrics:
  bindAddress: 127.0.0.1:8080
webhook:
  port: 9443
leaderElection:
  leaderElect: true
  resourceName: 95f0db32.company.org
