# permissions for end users to edit pubsublisteners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pubsublistener-editor-role
rules:
- apiGroups:
  - webapp.company.org
  resources:
  - pubsublisteners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.company.org
  resources:
  - pubsublisteners/status
  verbs:
  - get
