# permissions for end users to view pubsublisteners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pubsublistener-viewer-role
rules:
- apiGroups:
  - webapp.company.org
  resources:
  - pubsublisteners
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.company.org
  resources:
  - pubsublisteners/status
  verbs:
  - get
