apiVersion: batch.company.org/v1
kind: PubSubListener
metadata:
  labels:
    app: pubsubpuller
    app/listener: pubsublistener
    tier: backend
  name: pubsubpuller
  namespace: roster-sync
spec:
  selector:
    matchLabels:
      app: pubsubpuller
      app/listener: pubsublistener
      tier: backend
  template:
    metadata:
      labels:
        app: pubsubpuller
        app/listener: pubsublistener
        tier: backend
    spec:
      automountServiceAccountToken: true
      containers:
        - args:
            - pull-topic
            - -forever
          # command:
          # - /go/bin/main
          env:
            - name: DEBUG
              value: "TRUE"
            - name: LOCAL_BASEPATH
              value: /scratch
            - name: KA_IS_DEV_SERVER
              value: "0"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /config/secret/service-account-credentials.json
          image: gcr.io/khan-internal-services/districts-jobs-roster:50e642a40dd5ab694b29029cde309c19c4609695
          imagePullPolicy: Always
          name: pubsubpuller
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: "1"
              memory: 2Gi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            readOnlyRootFilesystem: true
            runAsGroup: 65534
            runAsUser: 65534
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: FallbackToLogsOnError
          volumeMounts:
            - mountPath: /config/secret
              name: service-account-credentials-vol
            - mountPath: /scratch
              name: scratch-vol
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      restartPolicy: Always
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir:
            medium: Memory
          name: scratch-vol
        - name: service-account-credentials-vol
          secret:
            defaultMode: 420
            optional: false
            secretName: service-account-credentials